# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokeMasters' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokeMasters
  pod 'Alamofire'
  pod 'Kingfisher', '~> 7.12'
  target 'PokeMastersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokeMastersUITests' do
    # Pods for testing
  end

end
